//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace GMapsTest.QiblahCalcWSStaging {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QiblahCalculatorWSSoap", Namespace="http://tempuri.org/")]
    public partial class QiblahCalculatorWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FindQiblahOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindQiblahStringOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QiblahCalculatorWS() {
            this.Url = global::GMapsTest.Properties.Settings.Default.GMapsTest_QiblahCalcWSStaging_QiblahCalculatorWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FindQiblahCompletedEventHandler FindQiblahCompleted;
        
        /// <remarks/>
        public event FindQiblahStringCompletedEventHandler FindQiblahStringCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindQiblah", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double FindQiblah(string address, bool gpsUsed) {
            object[] results = this.Invoke("FindQiblah", new object[] {
                        address,
                        gpsUsed});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void FindQiblahAsync(string address, bool gpsUsed) {
            this.FindQiblahAsync(address, gpsUsed, null);
        }
        
        /// <remarks/>
        public void FindQiblahAsync(string address, bool gpsUsed, object userState) {
            if ((this.FindQiblahOperationCompleted == null)) {
                this.FindQiblahOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindQiblahOperationCompleted);
            }
            this.InvokeAsync("FindQiblah", new object[] {
                        address,
                        gpsUsed}, this.FindQiblahOperationCompleted, userState);
        }
        
        private void OnFindQiblahOperationCompleted(object arg) {
            if ((this.FindQiblahCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindQiblahCompleted(this, new FindQiblahCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindQiblahString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FindQiblahString(string address, bool gpsUsed) {
            object[] results = this.Invoke("FindQiblahString", new object[] {
                        address,
                        gpsUsed});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FindQiblahStringAsync(string address, bool gpsUsed) {
            this.FindQiblahStringAsync(address, gpsUsed, null);
        }
        
        /// <remarks/>
        public void FindQiblahStringAsync(string address, bool gpsUsed, object userState) {
            if ((this.FindQiblahStringOperationCompleted == null)) {
                this.FindQiblahStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindQiblahStringOperationCompleted);
            }
            this.InvokeAsync("FindQiblahString", new object[] {
                        address,
                        gpsUsed}, this.FindQiblahStringOperationCompleted, userState);
        }
        
        private void OnFindQiblahStringOperationCompleted(object arg) {
            if ((this.FindQiblahStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindQiblahStringCompleted(this, new FindQiblahStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void FindQiblahCompletedEventHandler(object sender, FindQiblahCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindQiblahCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindQiblahCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void FindQiblahStringCompletedEventHandler(object sender, FindQiblahStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindQiblahStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindQiblahStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591