// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.2032
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas {
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://earth.google.com/kml/2.0", IsNullable=false)]
    public class kml {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public kmlResponse[] Response;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    public class kmlResponse {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public kmlResponseStatus[] Status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public kmlResponsePlacemark[] Placemark;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    public class kmlResponseStatus {
        
        /// <remarks/>
        public string code;
        
        /// <remarks/>
        public string request;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    public class kmlResponsePlacemark {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string id;
        
        /// <remarks/>
        public string address;
        
        /// <remarks/>
        public kmlResponsePlacemarkAddressDetails AddressDetails;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public kmlResponsePlacemarkPoint[] Point;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    public class kmlResponsePlacemarkAddressDetails {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0")]
        public string Accuracy;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earth.google.com/kml/2.0")]
    public class kmlResponsePlacemarkPoint {
        
        /// <remarks/>
        public string coordinates;
    }
}
