//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prayttmobile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("prayttmobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DataSet1 xmlns=&quot;http://www.tempuri.org/DataSet1.xsd&quot;&gt;
        ///  &lt;loctest&gt;
        ///    &lt;city&gt;AALBORG&lt;/city&gt;
        ///    &lt;country&gt;DENMARK&lt;/country&gt;
        ///    &lt;diff&gt;20:36&lt;/diff&gt;
        ///    &lt;green&gt;+01:00:00&lt;/green&gt;
        ///    &lt;la_dir&gt;NORTH&lt;/la_dir&gt;
        ///    &lt;latitude&gt;57.6&lt;/latitude&gt;
        ///    &lt;lo_dir&gt;EAST&lt;/lo_dir&gt;
        ///    &lt;longitude&gt;9.51&lt;/longitude&gt;
        ///    &lt;sign&gt;+1&lt;/sign&gt;
        ///    &lt;sn&gt;2&lt;/sn&gt;
        ///  &lt;/loctest&gt;
        ///  &lt;loctest&gt;
        ///    &lt;city&gt;AARHUS&lt;/city&gt;
        ///    &lt;country&gt;DENMARK&lt;/country&gt;
        ///    &lt;diff&gt;17:32&lt;/diff&gt;
        ///    &lt;green&gt;+01:00:00&lt;/green [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locdata {
            get {
                return ResourceManager.GetString("locdata", resourceCulture);
            }
        }
    }
}
